# join()
thread.join()用于等待线程执行完成，调用thread.join()的位置需要注意，std::thread创建后，join()执行前，如果抛出异常，栈展开将自动调用std::thread析构函数，如果此时std::thread对应的线程没有结束，则程序自动调用std::terminate导致程序异常退出

## std::terminate
在 C++中，`std::terminate`是标准库中的一个函数，它用于异常终止程序的执行。

当出现某些严重错误情况，并且程序无法继续安全地运行时，就会调用`std::terminate`。一些可能导致`std::terminate`被调用的情况包括：

1. 未捕获的异常：当一个异常被抛出但没有合适的`catch`块来处理它时，默认情况下会导致`std::terminate`被调用。例如：
   ```cpp
   int main() {
       throw 5; // 抛出一个整数类型的异常，没有对应的 catch 块处理
       return 0;
   }
   ```
   在这个例子中，因为没有处理`int`类型异常的`catch`块，程序会调用`std::terminate`来终止执行。

2. 某些标准库函数内部的错误情况：例如，在动态内存分配失败（当`new`操作无法分配足够的内存时）且没有合适的处理机制时，可能会导致`std::terminate`被调用。

当`std::terminate`被调用时，它会执行一些默认的操作来清理资源并终止程序。默认情况下，它可能会调用`std::abort`，这将立即终止程序而不进行任何进一步的清理（例如，不会调用局部对象的析构函数等）。不过，可以通过设置自定义的`std::terminate_handler`来改变`std::terminate`的行为，例如进行更详细的错误记录等操作后再终止程序。

总之，`std::terminate`是 C++中用于处理严重错误情况并终止程序的一种机制，但应该尽量避免让它被调用，通过合适的错误处理和异常处理机制来保证程序的稳定性和正确性。

